//! The committed C header against the exports it describes.
//!
//! `include/tinker_pdf.h` is generated by cbindgen and committed, because a
//! C, Go or Swift caller needs it in the tree and `cargo build` runs nothing
//! outside rustc (CONTRIBUTING.md). A committed generated file drifts the day
//! somebody adds an export and forgets to regenerate, and the Go binding — the
//! one that compiles against the header rather than transcribing it — would
//! then fail to link a function the header never mentioned, or worse, compile
//! against a declaration that names nothing.
//!
//! So this reads both as text and compares the *names*: every `#[no_mangle]`
//! function in `src/` is declared in the header, and every function the header
//! declares is one of them. It spawns nothing (ruling 13; `cargo xtask
//! oracles`). What it cannot see is a signature that moved under an unchanged
//! name, which is why CI's `bindings` job also regenerates the header and
//! fails on any difference.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn crate_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

/// Every Rust source file under `src/`, recursively.
fn sources(dir: &Path, out: &mut Vec<PathBuf>) {
    let mut entries: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("reading {}: {e}", dir.display()))
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            sources(&path, out);
        } else if path.extension().is_some_and(|ext| ext == "rs") {
            out.push(path);
        }
    }
}

/// The name of every function exported with `#[no_mangle]`.
fn exported() -> BTreeSet<String> {
    let mut files = Vec::new();
    sources(&crate_root().join("src"), &mut files);
    let mut names = BTreeSet::new();
    for file in files {
        let text = std::fs::read_to_string(&file).expect("source is UTF-8");
        let mut armed = false;
        for line in text.lines() {
            let line = line.trim();
            if line == "#[no_mangle]" {
                armed = true;
                continue;
            }
            if armed && !line.starts_with("#[") && !line.starts_with("///") {
                armed = false;
                if let Some(rest) = line.split("extern \"C\" fn ").nth(1) {
                    let name: String = rest
                        .chars()
                        .take_while(|c| c.is_ascii_alphanumeric() || *c == '_')
                        .collect();
                    names.insert(name);
                }
            }
        }
    }
    names
}

/// The name of every function the header declares: an identifier starting
/// `tpdf_` immediately followed by `(`, outside comments.
fn declared() -> BTreeSet<String> {
    let header = std::fs::read_to_string(crate_root().join("include/tinker_pdf.h"))
        .expect("the header is committed");
    let mut names = BTreeSet::new();
    for line in header.lines() {
        let code = line.split("//").next().unwrap_or("");
        let bytes = code.as_bytes();
        let mut start = 0;
        while let Some(found) = code[start..].find("tpdf_") {
            let begin = start + found;
            let boundary = begin == 0 || {
                let before = bytes[begin - 1];
                !(before.is_ascii_alphanumeric() || before == b'_')
            };
            let end = begin
                + code[begin..]
                    .bytes()
                    .take_while(|b| b.is_ascii_alphanumeric() || *b == b'_')
                    .count();
            if boundary && code[end..].starts_with('(') {
                names.insert(code[begin..end].to_string());
            }
            start = end;
        }
    }
    names
}

#[test]
fn the_header_declares_every_export_and_nothing_else() {
    let exported = exported();
    let declared = declared();
    assert!(
        exported.len() > 100,
        "the scan found {} exports, which means it is not reading the sources",
        exported.len()
    );
    let missing: Vec<_> = exported.difference(&declared).collect();
    let stale: Vec<_> = declared.difference(&exported).collect();
    assert!(
        missing.is_empty() && stale.is_empty(),
        "include/tinker_pdf.h is out of step with src/ — regenerate it with \
         the command in cbindgen.toml.\n  exported but not declared: {missing:?}\n  \
         declared but not exported: {stale:?}"
    );
}

/// The scanner is held to a known answer, so a header and a source tree that
/// both scan as empty cannot agree their way to a pass.
#[test]
fn the_scan_finds_the_functions_everybody_calls() {
    for name in [
        "tpdf_document_open",
        "tpdf_last_error_message",
        "tpdf_document_outline",
        "tpdf_warnings_free",
    ] {
        assert!(exported().contains(name), "{name} exported");
        assert!(declared().contains(name), "{name} declared");
    }
}
