//! Compiles Adobe's vendored CMap registry into two static tables.
//!
//! `docs/plans/05-fonts.md` specifies this: the predefined CMaps of 9.7.5.2
//! are "parsed at build time from Adobe's `cmap-resources` data", as
//! "delta-encoded ranges, deflated with our own filter code". This is that
//! build step, and it is the first `build.rs` in the workspace.
//!
//! # What comes out
//!
//! Two files in `OUT_DIR`, and the split between them is the whole shape of
//! the `cmap-predefined` feature.
//!
//! `cmap_names.bin` — every CMap's **name, writing mode, `usecmap` parent and
//! codespace ranges**, uncompressed, about ten kilobytes. Always compiled in.
//! Codespaces are what decide where one code ends and the next begins, so a
//! build carrying only this still splits a Shift-JIS string in the right
//! places and still gets the advances right; what it does not know is which
//! CID each code means, and `CMap::is_approximate` is how it says so.
//!
//! `cmap_cids.bin` — the code-to-CID tables, one deflate stream per CMap,
//! about a megabyte. Only written when `cmap-predefined` is on, which is why
//! `tinker-pdf-filters` is an *optional* dependency: with the feature off
//! there is nothing to inflate and the edge does not exist.
//!
//! # Panicking is correct here
//!
//! Ruling 1 binds code that reads *documents*. This reads a directory that
//! ships in the repository and is checked by `cargo xtask vendor`. A CMap
//! that does not parse, a range that overlaps another, a `usecmap` naming a
//! file that is not there — each of those is a broken checkout or a bad
//! vendoring, and failing the build is the only useful response. Nothing this
//! file does runs at document-reading time.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

/// Where the vendored registry lives, relative to the crate root.
const DATA: &str = "data/cmap-resources";

fn main() {
    let root = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this"));
    let data = root.join(DATA);

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", data.display());

    let mut sources = Vec::new();
    collect(&data, &mut sources);
    sources.sort();
    assert!(
        !sources.is_empty(),
        "no CMaps under {} -- the vendored data is missing",
        data.display()
    );

    // Sorted by name, so a lookup is a scan over a table that is at least
    // predictable, and so the generated bytes do not depend on the order the
    // filesystem happened to hand them over. A build that is not
    // reproducible is a build whose output nobody can compare.
    let mut parsed: BTreeMap<String, Cmap> = BTreeMap::new();
    for path in &sources {
        println!("cargo:rerun-if-changed={}", path.display());
        let name = path
            .file_name()
            .expect("collect() only yields files")
            .to_string_lossy()
            .into_owned();
        let cmap = parse(
            &std::fs::read(path).expect("vendored file is readable"),
            &name,
        );
        assert!(
            parsed.insert(name.clone(), cmap).is_none(),
            "two collections both define {name}"
        );
    }

    let index: BTreeMap<&str, u16> = parsed
        .keys()
        .enumerate()
        .map(|(i, name)| {
            (
                name.as_str(),
                u16::try_from(i).expect("the registry is 202 CMaps, not 65 536"),
            )
        })
        .collect();

    let mut names = Vec::new();
    let mut cids: Vec<Vec<u8>> = Vec::new();
    push_u32(&mut names, parsed.len() as u32);
    for (name, cmap) in &parsed {
        let parent = match &cmap.parent {
            // A parent outside the vendored set would silently become "no
            // parent", and a differential CMap with no parent is the defect
            // gap 04 exists for. There is no such parent today; this is what
            // says so if a future re-vendoring drops one.
            Some(p) => *index
                .get(p.as_str())
                .unwrap_or_else(|| panic!("{name} uses {p}, which is not vendored")),
            None => u16::MAX,
        };
        names.push(u8::try_from(name.len()).expect("registry names are short"));
        names.extend_from_slice(name.as_bytes());
        names.push(u8::from(cmap.vertical) | (u8::from(cmap.wmode_declared) << 1));
        names.extend_from_slice(&parent.to_le_bytes());
        names.push(u8::try_from(cmap.codespaces.len()).expect("no CMap declares 256 codespaces"));
        for (bytes, low, high) in &cmap.codespaces {
            names.push(*bytes);
            push_varint(&mut names, u64::from(*low));
            push_varint(&mut names, u64::from(*high - *low));
        }
        cids.push(encode_ranges(name, cmap));
    }
    std::fs::write(out.join("cmap_names.bin"), &names).expect("OUT_DIR is writable");

    // The CID half only exists when something will inflate it.
    let enabled = std::env::var_os("CARGO_FEATURE_CMAP_PREDEFINED").is_some();
    let mut blob = Vec::new();
    if enabled {
        push_u32(&mut blob, cids.len() as u32);
        let mut payload = Vec::new();
        for table in &cids {
            // zlib rather than raw deflate: the six-byte wrapper buys an
            // Adler-32 over our own generated bytes, and the decoder warns
            // `RawDeflateFallback` on a bare stream, which would be a warning
            // per lookup about nothing.
            let packed = tinker_pdf_filters::zlib_compress(table);
            push_u32(&mut blob, payload.len() as u32);
            push_u32(&mut blob, packed.len() as u32);
            payload.extend_from_slice(&packed);
        }
        blob.extend_from_slice(&payload);
    }
    std::fs::write(out.join("cmap_cids.bin"), &blob).expect("OUT_DIR is writable");
}

/// Every file directly inside a `CMap/` directory, at any depth.
fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect(&path, out);
        } else if dir.file_name().is_some_and(|d| d == "CMap") {
            out.push(path);
        }
    }
}

/// One CMap, as the registry states it.
#[derive(Default)]
struct Cmap {
    /// `(byte length, low, high)`, in declaration order.
    codespaces: Vec<(u8, u32, u32)>,
    /// `(low, high, first CID)`, `cidchar` folded in as a one-code range.
    ranges: Vec<(u32, u32, u32)>,
    parent: Option<String>,
    vertical: bool,
    wmode_declared: bool,
}

/// Delta-encodes one CMap's ranges.
///
/// Sorted by low code, so the low delta is never negative and the runtime can
/// binary-search instead of scanning: `UniCNS-UTF8-H` is 18 568 ranges, and a
/// linear scan of that per character is the difference between CJK text
/// rendering and CJK text rendering slowly.
///
/// The sort is only sound because the ranges are disjoint, which is asserted
/// rather than assumed. If a `cidchar` ever fell inside one of its own CMap's
/// `cidrange`s, sorting would put the range first and the single would stop
/// winning -- silently, and in the direction that produces a plausible wrong
/// glyph. No CMap in the vendored set does this; 202 of them were checked by
/// this assertion the first time it ran.
fn encode_ranges(name: &str, cmap: &Cmap) -> Vec<u8> {
    let mut ranges = cmap.ranges.clone();
    ranges.sort_unstable();
    for pair in ranges.windows(2) {
        assert!(
            pair[1].0 > pair[0].1,
            "{name}: {:04X?} and {:04X?} overlap, so sorting them changes which wins",
            pair[0],
            pair[1]
        );
    }

    let mut out = Vec::new();
    push_varint(&mut out, ranges.len() as u64);
    let (mut prev_low, mut prev_cid) = (0u32, 0u32);
    for (low, high, cid) in ranges {
        push_varint(&mut out, u64::from(low - prev_low));
        push_varint(&mut out, u64::from(high - low));
        push_varint(&mut out, zigzag(i64::from(cid) - i64::from(prev_cid)));
        prev_low = low;
        prev_cid = cid;
    }
    out
}

fn zigzag(v: i64) -> u64 {
    ((v << 1) ^ (v >> 63)) as u64
}

fn push_varint(out: &mut Vec<u8>, mut value: u64) {
    loop {
        let byte = (value & 0x7F) as u8;
        value >>= 7;
        if value == 0 {
            out.push(byte);
            return;
        }
        out.push(byte | 0x80);
    }
}

fn push_u32(out: &mut Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_le_bytes());
}

// ---------------------------------------------------------------------------
// The scanner
// ---------------------------------------------------------------------------

/// The subset of PostScript a CMap resource actually uses.
#[derive(Debug, PartialEq, Eq)]
enum Token {
    Hex(Vec<u8>),
    Name(String),
    Number(i64),
    Keyword(String),
}

/// Reads one vendored CMap.
///
/// `notdefrange` is deliberately not read. It names the CID to substitute for
/// a code that is inside a codespace and mapped by nothing, which in every
/// vendored CMap is the collection's space or notdef glyph -- so honouring it
/// would replace "this code means nothing" with a guess that happens to look
/// like a real answer. Leaving those codes unmapped is the same choice this
/// gap makes everywhere else.
fn parse(bytes: &[u8], name: &str) -> Cmap {
    let mut cmap = Cmap::default();
    let mut tokens = Tokenizer { bytes, pos: 0 };
    let mut stack: Vec<Token> = Vec::new();

    while let Some(token) = tokens.next_token() {
        let Token::Keyword(word) = &token else {
            stack.push(token);
            if stack.len() > 4 {
                stack.remove(0);
            }
            continue;
        };
        match word.as_str() {
            "begincodespacerange" => {
                for record in section(&mut tokens, "endcodespacerange", 2, name) {
                    let (Token::Hex(low), Token::Hex(high)) = (&record[0], &record[1]) else {
                        panic!("{name}: a codespace range that is not two hex strings");
                    };
                    let width = low.len();
                    assert!(
                        (1..=4).contains(&width) && high.len() == width,
                        "{name}: a codespace range whose bounds are {width} and {} bytes",
                        high.len()
                    );
                    cmap.codespaces.push((width as u8, be(low), be(high)));
                }
            }
            "begincidrange" => {
                for record in section(&mut tokens, "endcidrange", 3, name) {
                    let (Token::Hex(low), Token::Hex(high), Token::Number(cid)) =
                        (&record[0], &record[1], &record[2])
                    else {
                        panic!("{name}: a cidrange that is not <low> <high> cid");
                    };
                    cmap.ranges.push((
                        be(low),
                        be(high),
                        u32::try_from(*cid).expect("a CID is not negative"),
                    ));
                }
            }
            "begincidchar" => {
                for record in section(&mut tokens, "endcidchar", 2, name) {
                    let (Token::Hex(code), Token::Number(cid)) = (&record[0], &record[1]) else {
                        panic!("{name}: a cidchar that is not <code> cid");
                    };
                    cmap.ranges.push((
                        be(code),
                        be(code),
                        u32::try_from(*cid).expect("a CID is not negative"),
                    ));
                }
            }
            "beginnotdefrange" => {
                let _ = section(&mut tokens, "endnotdefrange", 3, name);
            }
            "usecmap" => {
                if let Some(Token::Name(parent)) = stack.last() {
                    cmap.parent = Some(parent.clone());
                }
                stack.clear();
            }
            "def" => {
                if let (Some(Token::Number(n)), Some(Token::Name(key))) =
                    (stack.last(), stack.get(stack.len().wrapping_sub(2)))
                {
                    if key == "WMode" {
                        cmap.vertical = *n == 1;
                        cmap.wmode_declared = true;
                    }
                }
                stack.clear();
            }
            _ => stack.clear(),
        }
    }

    assert!(
        !cmap.codespaces.is_empty() || cmap.parent.is_some(),
        "{name}: no codespace ranges and no usecmap, so it can split nothing"
    );
    cmap
}

/// Reads records of `width` tokens until `end`.
fn section(tokens: &mut Tokenizer, end: &str, width: usize, name: &str) -> Vec<Vec<Token>> {
    let mut out = Vec::new();
    let mut record = Vec::new();
    loop {
        let token = tokens
            .next_token()
            .unwrap_or_else(|| panic!("{name}: input ended inside a section wanting {end}"));
        if token == Token::Keyword(end.to_string()) {
            assert!(record.is_empty(), "{name}: {end} in the middle of a record");
            return out;
        }
        record.push(token);
        if record.len() == width {
            out.push(std::mem::take(&mut record));
        }
    }
}

fn be(bytes: &[u8]) -> u32 {
    bytes.iter().fold(0u32, |a, &b| (a << 8) | u32::from(b))
}

struct Tokenizer<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl Tokenizer<'_> {
    fn next_token(&mut self) -> Option<Token> {
        loop {
            let b = *self.bytes.get(self.pos)?;
            if b.is_ascii_whitespace() {
                self.pos += 1;
                continue;
            }
            // Every vendored file opens with forty lines of `%%Copyright`.
            if b == b'%' {
                while self
                    .bytes
                    .get(self.pos)
                    .is_some_and(|&c| c != b'\n' && c != b'\r')
                {
                    self.pos += 1;
                }
                continue;
            }
            break;
        }

        let b = *self.bytes.get(self.pos)?;
        match b {
            b'<' => {
                self.pos += 1;
                let start = self.pos;
                while self.bytes.get(self.pos).is_some_and(|&c| c != b'>') {
                    self.pos += 1;
                }
                let text = &self.bytes[start..self.pos];
                self.pos += 1;
                let digits: Vec<u8> = text
                    .iter()
                    .filter(|c| !c.is_ascii_whitespace())
                    .copied()
                    .collect();
                assert!(
                    digits.len() % 2 == 0 && digits.iter().all(u8::is_ascii_hexdigit),
                    "a hex string with an odd or non-hex body"
                );
                Some(Token::Hex(
                    digits
                        .chunks_exact(2)
                        .map(|p| {
                            let hi = (p[0] as char).to_digit(16).expect("checked above") as u8;
                            let lo = (p[1] as char).to_digit(16).expect("checked above") as u8;
                            (hi << 4) | lo
                        })
                        .collect(),
                ))
            }
            b'/' => {
                self.pos += 1;
                Some(Token::Name(self.word()))
            }
            b'0'..=b'9' | b'-' | b'+' | b'.' => {
                let word = self.word();
                // `/CMapVersion 11.006 def` is a real number and nothing reads
                // it; only the integers matter.
                Some(Token::Number(word.parse::<i64>().unwrap_or(0)))
            }
            b'[' | b']' | b'(' | b')' | b'{' | b'}' => {
                self.pos += 1;
                Some(Token::Keyword(String::from(b as char)))
            }
            _ => Some(Token::Keyword(self.word())),
        }
    }

    /// Bytes up to the next delimiter or space.
    fn word(&mut self) -> String {
        let start = self.pos;
        while self.bytes.get(self.pos).is_some_and(|&c| {
            !c.is_ascii_whitespace()
                && !matches!(
                    c,
                    b'(' | b')' | b'<' | b'>' | b'[' | b']' | b'{' | b'}' | b'/' | b'%'
                )
        }) {
            self.pos += 1;
        }
        if self.pos == start {
            self.pos += 1;
        }
        String::from_utf8_lossy(&self.bytes[start..self.pos]).into_owned()
    }
}
