//! Compiles the vendored UCD into static range tables.
//!
//! `crates/tinker-pdf-layout/build.rs` does the same job for UAX #14 and this
//! file is deliberately in its register: text files in, one `.rs` out, and
//! nothing under `data/ucd` is opened at run time. THIRDPARTY.md's promise
//! about vendored data — *"the raw files never reach a released binary"* — is
//! kept the same way here.
//!
//! # The classes are emitted as enum variants, not as indices
//!
//! Every row of the generated table names `BidiClass::AL` rather than the
//! number `2`, and every script row names `Script::Ethiopic`. That costs a few
//! bytes of generated source and buys the thing an index cannot: **a
//! Bidi_Class or a Script this crate does not know about fails to build.**
//!
//! It is not a hypothetical. Unicode 6.3 added the four isolate classes —
//! `LRI`, `RLI`, `FSI`, `PDI` — and an implementation that mapped an unknown
//! class name onto a default would have resolved every isolate as `ON`, which
//! is a paragraph that reorders plausibly and wrongly. Unicode 17.0 added
//! scripts to `Scripts.txt`; a shaper that silently gave a new script the
//! default shaper would set it as though the addition had never happened. In
//! both cases the correct outcome of re-vendoring a later UCD is a build that
//! stops until somebody reads the new value.
//!
//! # What each file is for
//!
//! - `DerivedBidiClass.txt` is the `Bidi_Class` property, which **is** UAX #9.
//! - `BidiBrackets.txt` is `Bidi_Paired_Bracket` and
//!   `Bidi_Paired_Bracket_Type`, which rule N0 is written in terms of.
//! - `BidiMirroring.txt` is `Bidi_Mirroring_Glyph`, rule L4.
//! - `Scripts.txt` is UAX #24's `Script` property, which is what itemization
//!   splits a paragraph on.
//! - `PropertyValueAliases.txt` supplies each script's ISO 15924 code, which
//!   is where an OpenType script tag comes from. See
//!   [`crate::unicode::Script::opentype_tag`] for what that derivation does
//!   and does not cover.
//!
//! `BidiTest.txt` and `BidiCharacterTest.txt` are **not** read here. They are
//! the conformance oracle and they are read by a test, because a table
//! compiled from its own test data would prove nothing.
//!
//! # `@missing` lines are applied here and were not in the layout crate
//!
//! The two files disagree about their own defaults and both are right about
//! themselves. `LineBreak.txt` writes its block defaults out as explicit rows,
//! so `tinker-pdf-layout/build.rs` records — at length — that applying them a
//! second time breaks ten conformance cases. `DerivedBidiClass.txt` does the
//! opposite: its header says in as many words that *"unassigned code points in
//! blocks reserved for right-to-left scripts are given either values R or
//! AL"*, and those code points are **not** in the file. Skipping the `@missing`
//! lines here would give every unassigned code point in the Hebrew block the
//! class `L`, and a Hebrew paragraph containing one would reorder around it.
//!
//! So the rule is not "always apply defaults" or "never" — it is *read the
//! file's own header*, which is why both build scripts say which they do.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let data = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .join("data")
        .join("ucd");
    for file in [
        "DerivedBidiClass.txt",
        "BidiBrackets.txt",
        "BidiMirroring.txt",
        "Scripts.txt",
        "PropertyValueAliases.txt",
        "DerivedJoiningType.txt",
    ] {
        println!("cargo:rerun-if-changed=data/ucd/{file}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::new();
    out.push_str("// Generated by build.rs from the vendored UCD. Do not edit.\n");

    bidi_class(&data, &mut out);
    brackets(&data, &mut out);
    mirroring(&data, &mut out);
    scripts(&data, &mut out);
    joining(&data, &mut out);

    let target = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("ucd.rs");
    std::fs::write(&target, out).expect("the generated table could not be written");
}

/// One `code..code ; value # comment` file, as `(first, last, value)`.
///
/// The UCD's own format. Two things are worth being careful about and both
/// occur in these files: the published files are CRLF, and a `#` may either
/// start a comment line or end a value.
fn rows(path: &Path) -> Vec<(u32, u32, Vec<String>)> {
    let text = read(path);
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end_matches('\r');
        let body = match line.find('#') {
            Some(0) => continue,
            Some(at) => &line[..at],
            None => line,
        };
        let mut fields = body.split(';');
        let Some(codes) = fields.next() else {
            continue;
        };
        let values: Vec<String> = fields.map(|f| f.trim().to_string()).collect();
        if values.is_empty() || values[0].is_empty() {
            continue;
        }
        let codes = codes.trim();
        if codes.is_empty() {
            continue;
        }
        let (first, last) = match codes.split_once("..") {
            Some((a, b)) => (hex(a), hex(b)),
            None => (hex(codes), hex(codes)),
        };
        out.push((first, last, values));
    }
    assert!(!out.is_empty(), "no rows in {}", path.display());
    out
}

/// The `# @missing: 0590..05FF; Right_To_Left` lines, in file order.
///
/// They are comments, so [`rows`] skips them, and they are load-bearing: see
/// this file's header for why this one property needs them and the layout
/// crate's does not.
fn missing(path: &Path) -> Vec<(u32, u32, String)> {
    let text = read(path);
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end_matches('\r');
        let Some(body) = line
            .trim_start_matches('#')
            .trim()
            .strip_prefix("@missing:")
        else {
            continue;
        };
        let Some((codes, value)) = body.split_once(';') else {
            continue;
        };
        let (first, last) = match codes.trim().split_once("..") {
            Some((a, b)) => (hex(a), hex(b)),
            None => (hex(codes.trim()), hex(codes.trim())),
        };
        out.push((first, last, value.trim().to_string()));
    }
    assert!(!out.is_empty(), "no @missing lines in {}", path.display());
    out
}

fn read(path: &Path) -> String {
    std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("the vendored UCD is missing: {} ({e})", path.display()))
}

fn hex(text: &str) -> u32 {
    u32::from_str_radix(text.trim(), 16)
        .unwrap_or_else(|e| panic!("{text:?} is not a code point ({e})"))
}

/// Merges a code-point map into the fewest sorted ranges that describe it.
fn ranges(map: &BTreeMap<u32, String>) -> Vec<(u32, u32, String)> {
    let mut out: Vec<(u32, u32, String)> = Vec::new();
    for (code, value) in map {
        match out.last_mut() {
            Some((_, last, previous)) if *last + 1 == *code && previous == value => *last = *code,
            _ => out.push((*code, *code, value.clone())),
        }
    }
    out
}

/// `Bidi_Class`, with the header's own block defaults applied first.
///
/// The full 0..=0x10FFFF space is filled rather than only the assigned part,
/// because the defaults are the whole point: an unassigned code point in
/// `0590..05FF` is `R`, and a table that answered `L` for it would put a
/// reserved Hebrew code point on the wrong side of the line.
fn bidi_class(data: &Path, out: &mut String) {
    let path = data.join("DerivedBidiClass.txt");
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    // In file order: `0000..10FFFF; Left_To_Right` comes first and the block
    // defaults that follow narrow it.
    for (first, last, value) in missing(&path) {
        for code in first..=last {
            map.insert(code, abbreviate(&value));
        }
    }
    for (first, last, values) in rows(&path) {
        for code in first..=last {
            map.insert(code, values[0].clone());
        }
    }
    let merged = ranges(&map);
    assert_eq!(
        merged.first().map(|r| r.0),
        Some(0),
        "the Bidi_Class table does not start at U+0000"
    );
    assert_eq!(
        merged.last().map(|r| r.1),
        Some(0x0010_FFFF),
        "the Bidi_Class table does not reach U+10FFFF"
    );
    emit(out, "BIDI_CLASS", "BidiClass", &merged);
}

/// The long `Bidi_Class` names the `@missing` lines use, as the abbreviations
/// the data rows use.
///
/// `PropertyValueAliases.txt` states this correspondence, and it is read from
/// there rather than written out, so a name this build script has never seen
/// stops the build in the same way an unknown class does.
fn abbreviate(long: &str) -> String {
    // The alias file is read once per call rather than threaded through, and
    // the number of `@missing` lines is twenty-five.
    let path = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .join("data")
        .join("ucd")
        .join("PropertyValueAliases.txt");
    for line in read(&path).lines() {
        let line = line.trim_end_matches('\r');
        let body = match line.find('#') {
            Some(0) => continue,
            Some(at) => &line[..at],
            None => line,
        };
        let fields: Vec<&str> = body.split(';').map(str::trim).collect();
        if fields.len() >= 3 && fields[0] == "bc" && fields[2] == long {
            return fields[1].to_string();
        }
    }
    panic!("PropertyValueAliases.txt has no bc alias for {long:?}");
}

/// `Bidi_Paired_Bracket` and `Bidi_Paired_Bracket_Type`, as
/// `(code, paired, kind)`.
///
/// Sorted by code so the crate can binary-search it, and the pair is carried
/// beside the kind because rule N0 needs both at once: it asks whether the
/// character it is looking at opens a pair and, if so, which character closes
/// it.
fn brackets(data: &Path, out: &mut String) {
    let mut body = String::new();
    let mut count = 0usize;
    let mut previous = 0u32;
    for (first, last, values) in rows(&data.join("BidiBrackets.txt")) {
        assert_eq!(first, last, "BidiBrackets.txt gained a range");
        assert!(
            count == 0 || first > previous,
            "BidiBrackets.txt is not sorted at {first:#x}"
        );
        previous = first;
        let paired = hex(&values[0]);
        let kind = match values.get(1).map(String::as_str) {
            Some("o") => "BracketKind::Open",
            Some("c") => "BracketKind::Close",
            // `n` is in the property's value set and no character carries it;
            // anything else is a value this crate has never seen, and both
            // stop the build rather than being mapped onto a default.
            other => panic!("BidiBrackets.txt has bracket type {other:?}"),
        };
        let _ = writeln!(body, "    ({first:#x}, {paired:#x}, {kind}),");
        count += 1;
    }
    let _ = writeln!(
        out,
        "/// {count} bracket pairs, from the vendored UCD: `(code, paired, kind)`.\n\
         pub static BRACKETS: &[(u32, u32, BracketKind)] = &[\n{body}];",
    );
}

/// `Bidi_Mirroring_Glyph`, as `(code, mirrored)`.
fn mirroring(data: &Path, out: &mut String) {
    let mut body = String::new();
    let mut count = 0usize;
    let mut previous = 0u32;
    for (first, last, values) in rows(&data.join("BidiMirroring.txt")) {
        assert_eq!(first, last, "BidiMirroring.txt gained a range");
        assert!(
            count == 0 || first > previous,
            "BidiMirroring.txt is not sorted at {first:#x}"
        );
        previous = first;
        let mirrored = hex(&values[0]);
        let _ = writeln!(body, "    ({first:#x}, {mirrored:#x}),");
        count += 1;
    }
    let _ = writeln!(
        out,
        "/// {count} mirrored characters, from the vendored UCD.\n\
         pub static MIRRORING: &[(u32, u32)] = &[\n{body}];",
    );
}

/// UAX #24's `Script`, and each script's ISO 15924 code.
///
/// `Scripts.txt` states no default of its own beyond `Unknown`, so a code
/// point the file does not list is `Script::Unknown` and the table is sparse
/// rather than complete.
fn scripts(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, values) in rows(&data.join("Scripts.txt")) {
        for code in first..=last {
            map.insert(code, values[0].clone());
        }
    }
    emit(out, "SCRIPT", "Script", &ranges(&map));

    // The ISO 15924 code, as a match rather than a table, so the two
    // directions both stop the build: a script in the alias file that the
    // enum does not have names an unknown variant, and a variant the alias
    // file does not cover leaves the match non-exhaustive.
    let path = data.join("PropertyValueAliases.txt");
    let mut arms = String::new();
    let mut count = 0usize;
    for line in read(&path).lines() {
        let line = line.trim_end_matches('\r');
        let body = match line.find('#') {
            Some(0) => continue,
            Some(at) => &line[..at],
            None => line,
        };
        let fields: Vec<&str> = body.split(';').map(str::trim).collect();
        if fields.len() < 3 || fields[0] != "sc" {
            continue;
        }
        let (code, long) = (fields[1], fields[2]);
        assert_eq!(code.len(), 4, "{code} is not an ISO 15924 code");
        // `Katakana_Or_Hiragana` (`Hrkt`) is a *union* value that no character
        // carries; it exists for the `Script_Extensions` property and
        // `Scripts.txt` never uses it. Carrying it would need an enum variant
        // that could not be produced, so it is dropped by name.
        if long == "Katakana_Or_Hiragana" {
            continue;
        }
        let _ = writeln!(arms, "        Script::{} => *b\"{code}\",", variant(long));
        count += 1;
    }
    let _ = writeln!(
        out,
        "/// The ISO 15924 code of each of the {count} scripts, from the \
         vendored UCD.\n\
         #[must_use]\n\
         pub const fn iso15924(script: Script) -> [u8; 4] {{\n    \
         match script {{\n{arms}    }}\n}}",
    );
}

/// The `Joining_Type` property, which Arabic cursive joining is written in.
///
/// # Why the derived file and not `ArabicShaping.txt`
///
/// The two carry the same property and state it differently.
/// `ArabicShaping.txt` lists the joining letters and leaves `Transparent`
/// implicit — *"those not explicitly listed and of General Category Mn, Me or
/// Cf have joining type T"* — so reading it means having `General_Category`,
/// which this crate does not vendor and does not otherwise need.
/// `extracted/DerivedJoiningType.txt` has already done that derivation and
/// lists all 386 `T` ranges outright, so the whole property is a table lookup
/// and there is no second rule for a transcription error to live in.
///
/// The `@missing` line is `Non_Joining`, unconditionally, so a code point the
/// file does not list is `U` and the table is sparse. That is unlike
/// `DerivedBidiClass.txt` one function up, whose `@missing` lines are
/// per-block and *are* applied; the difference is in the files and is why
/// both are read by hand rather than by one shared rule.
///
/// The `Joining_Group` property is deliberately not read. It is needed for
/// exactly one thing — Syriac's Alaph, which selects the `fin2`, `fin3` and
/// `med2` features rather than `fina` — and no fixture in either vendored
/// corpus contains a Syriac face, so implementing it would be adding
/// unadjudicated behavior. `docs/features/fonts.md` lists Syriac by name for
/// that reason.
fn joining(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, values) in rows(&data.join("DerivedJoiningType.txt")) {
        for code in first..=last {
            map.insert(code, values[0].clone());
        }
    }
    assert!(
        !map.is_empty(),
        "DerivedJoiningType.txt yielded no rows; the joining table would be \
         empty and every Arabic letter would shape as isolated"
    );
    emit(out, "JOINING", "JoiningType", &ranges(&map));
}

/// A UCD long name as a Rust variant name: `Caucasian_Albanian` becomes
/// `CaucasianAlbanian`.
fn variant(long: &str) -> String {
    long.split('_').collect::<String>()
}

fn emit(out: &mut String, name: &str, kind: &str, merged: &[(u32, u32, String)]) {
    let mut body = String::new();
    for (first, last, value) in merged {
        let value = if kind == "Script" {
            variant(value)
        } else {
            value.clone()
        };
        let _ = writeln!(body, "    ({first:#x}, {last:#x}, {kind}::{value}),");
    }
    let _ = writeln!(
        out,
        "/// {} ranges, from the vendored UCD. The value is an enum variant \
         rather than an index, so a value this crate does not know **does not \
         build**.\npub static {name}: &[(u32, u32, {kind})] = &[\n{body}];",
        merged.len()
    );
}
