//! Compiles the vendored UCD into static range tables.
//!
//! THIRDPARTY.md's promise about vendored data is that *"the raw files never
//! reach a released binary"*, and this is the half of it that keeps the
//! promise for this crate: text files in, one `.rs` out, and nothing under
//! `data/` is opened at run time. It is in the register of
//! `tinker-pdf-layout/build.rs`, which does the same for UAX #14 one crate
//! over — a **third** copy of the UCD rather than a share of either existing
//! one, because this crate may not depend on `tinker-pdf-layout` or
//! `tinker-pdf-shape` (`cargo xtask dag`) and a build script cannot read
//! across a crate boundary. The cost is version skew, and
//! `crates/tinker-pdf-shape/tests/ucd_version.rs` asserts it away for all
//! three trees.
//!
//! # What each file is for
//!
//! - `WordBreakProperty.txt` is UAX #29's `Word_Break` property, which is the
//!   word-boundary algorithm.
//! - `emoji-data.txt` is `Extended_Pictographic`, which rule WB3c is written
//!   in: a zero-width joiner followed by a pictograph is not a boundary.
//!
//! `WordBreakTest.txt` is not read here. It is the conformance oracle and it
//! is read by a test, because a table compiled from its own test data would
//! prove nothing.
//!
//! # The property is emitted as enum variants, not as indices
//!
//! Every row names `WordBreak::ALetter` rather than a number, so **a
//! `Word_Break` value this crate does not know fails to build** — the same
//! choice, for the same reason, as the line-break table's.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let data = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .join("data")
        .join("ucd");
    for file in ["WordBreakProperty.txt", "emoji-data.txt"] {
        println!("cargo:rerun-if-changed=data/ucd/{file}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::new();
    out.push_str("// Generated by build.rs from the vendored UCD. Do not edit.\n");

    word_break(&data, &mut out);
    binary_property(
        &data.join("emoji-data.txt"),
        "Extended_Pictographic",
        "EXTENDED_PICTOGRAPHIC",
        &mut out,
    );

    let target = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("ucd.rs");
    std::fs::write(&target, out).expect("the generated table could not be written");
}

/// One `code..code ; value # comment` file, as `(first, last, value)`.
///
/// The UCD's own format. The value may be followed by a `#` comment with no
/// space before it — `emoji-data.txt` writes `; Extended_Pictographic# E0.6`
/// — so the comment is cut before the fields are split.
fn rows(path: &Path) -> Vec<(u32, u32, String)> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("the vendored UCD is missing: {} ({e})", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end_matches('\r');
        let body = match line.find('#') {
            Some(0) => continue,
            Some(at) => &line[..at],
            None => line,
        };
        let mut fields = body.split(';');
        let (Some(codes), Some(value)) = (fields.next(), fields.next()) else {
            continue;
        };
        let value = value.trim();
        if value.is_empty() {
            continue;
        }
        let codes = codes.trim();
        let (first, last) = match codes.split_once("..") {
            Some((a, b)) => (hex(a), hex(b)),
            None => (hex(codes), hex(codes)),
        };
        out.push((first, last, value.to_string()));
    }
    assert!(!out.is_empty(), "no rows in {}", path.display());
    out
}

fn hex(text: &str) -> u32 {
    u32::from_str_radix(text.trim(), 16)
        .unwrap_or_else(|e| panic!("{text:?} is not a code point ({e})"))
}

/// Merges a code-point map into the fewest sorted ranges that describe it.
fn ranges(map: &BTreeMap<u32, String>) -> Vec<(u32, u32, String)> {
    let mut out: Vec<(u32, u32, String)> = Vec::new();
    for (code, value) in map {
        match out.last_mut() {
            Some((_, last, previous)) if *last + 1 == *code && previous == value => *last = *code,
            _ => out.push((*code, *code, value.clone())),
        }
    }
    out
}

/// The `Word_Break` property, exactly as the file states it.
///
/// Its one `@missing` line gives every unlisted code point `Other`, which is
/// also what a lookup that finds no range answers — so the default needs no
/// row, and a table that carried one would only be larger.
fn word_break(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(&data.join("WordBreakProperty.txt")) {
        for code in first..=last {
            map.insert(code, value.clone());
        }
    }
    let merged = ranges(&map);
    let mut body = String::new();
    for (first, last, value) in &merged {
        let variant = value.replace('_', "");
        let _ = writeln!(body, "    ({first:#x}, {last:#x}, WordBreak::{variant}),");
    }
    let _ = writeln!(
        out,
        "/// {} ranges, from the vendored UCD. The value is an enum variant \
         rather than an index, so a value this crate does not know **does not \
         build**.\npub(crate) static WORD_BREAK: &[(u32, u32, WordBreak)] = &[\n{body}];",
        merged.len()
    );
}

/// A file's rows whose value is one particular name, as bare ranges.
fn binary_property(path: &Path, wanted: &str, name: &str, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(path) {
        if value != wanted {
            continue;
        }
        for code in first..=last {
            map.insert(code, String::new());
        }
    }
    let merged = ranges(&map);
    assert!(
        !merged.is_empty(),
        "{} has no {wanted} rows",
        path.display()
    );
    let mut body = String::new();
    for (first, last, _) in &merged {
        let _ = writeln!(body, "    ({first:#x}, {last:#x}),");
    }
    let _ = writeln!(
        out,
        "/// {} ranges of {wanted}, from the vendored UCD.\n\
         pub(crate) static {name}: &[(u32, u32)] = &[\n{body}];",
        merged.len()
    );
}
