//! Compiles the vendored XHTML 1.0 entity sets into one sorted table.
//!
//! THIRDPARTY.md's promise about vendored data is that *"the raw files never
//! reach a released binary"*, and this is the half of it that keeps the
//! promise: three `.ent` files in, one `.rs` out, and nothing under `data/` is
//! opened at run time. `tinker-pdf-layout/build.rs` does the same for the UCD
//! and this file is deliberately in its register.
//!
//! # What is read, and what would fail the build
//!
//! Each file is a run of `<!ENTITY name "value" >` declarations between SGML
//! comments. The comments are stripped first — every file's header carries an
//! `<!ENTITY % … >` *example* inside one — and then every declaration left is a
//! general entity whose value is one character reference: `&#160;` in the
//! Latin-1 and symbol sets, and `&#38;#60;` for four of the five XML already
//! predefines, which is `&` written as a reference so the replacement text is
//! itself a reference (XML 1.0 §4.6's own advice for redeclaring them).
//!
//! Anything else stops the build rather than being skipped, because a table
//! that silently lost a row is a table whose absence nobody would see:
//!
//! - a declaration whose value is not one reference to one code point — which
//!   is what keeps a lookup from ever *expanding*: one name, one `char`;
//! - a code point XML 1.0 §2.2 does not admit as a character;
//! - a name declared twice, within a file or across the three;
//! - a total other than 253 — 96 Latin-1, 124 symbol, 33 special;
//! - **a name whose character is longer, in UTF-8, than `&name;` itself.**
//!   That is the crate's standing invariant — decoded text is never longer
//!   than its source — checked here for every row rather than argued once.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

/// The three sets, and how many declarations each must hold.
const SETS: [(&str, usize); 3] = [
    ("xhtml-lat1.ent", 96),
    ("xhtml-symbol.ent", 124),
    ("xhtml-special.ent", 33),
];

fn main() {
    let dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .join("data")
        .join("xhtml-entities");
    for (file, _) in SETS {
        println!("cargo:rerun-if-changed=data/xhtml-entities/{file}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut table: BTreeMap<String, u32> = BTreeMap::new();
    for (file, expected) in SETS {
        let path = dir.join(file);
        let text =
            std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
        let declared = declarations(&without_comments(&text), file);
        assert_eq!(
            declared.len(),
            expected,
            "{file} declares {} entities where the set holds {expected}",
            declared.len()
        );
        for (name, scalar) in declared {
            let c = char::from_u32(scalar)
                .unwrap_or_else(|| panic!("{file}: &{name}; is not a scalar value"));
            assert!(is_xml_char(c), "{file}: &{name}; is not an XML Char");
            assert!(
                c.len_utf8() <= name.len() + 2,
                "{file}: &{name}; decodes longer than its own reference"
            );
            assert!(
                table.insert(name.clone(), scalar).is_none(),
                "&{name}; is declared twice"
            );
        }
    }
    assert_eq!(table.len(), 253, "the three XHTML 1.0 sets hold 253 names");

    // Sorted by the name's bytes, which is what `BTreeMap<String, _>` iterates
    // in and what the lookup's binary search compares with.
    let mut out = String::new();
    out.push_str("// Generated by build.rs from data/xhtml-entities. Do not edit.\n");
    out.push_str(
        "/// The 253 names XHTML 1.0's three entity sets declare, sorted by name, \
         each with the one character it is.\n",
    );
    let _ = writeln!(
        out,
        "pub(crate) static XHTML_ENTITIES: [(&str, char); {}] = [",
        table.len()
    );
    for (name, scalar) in &table {
        let _ = writeln!(out, "    ({name:?}, '\\u{{{scalar:X}}}'),");
    }
    out.push_str("];\n");

    let target =
        PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("xhtml_entities.rs");
    std::fs::write(&target, out).unwrap_or_else(|e| panic!("{}: {e}", target.display()));
}

/// The text with every `<!-- … -->` removed.
fn without_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(open) = rest.find("<!--") {
        out.push_str(&rest[..open]);
        let after = &rest[open + 4..];
        let close = after
            .find("-->")
            .expect("an SGML comment that never closes");
        rest = &after[close + 3..];
    }
    out.push_str(rest);
    out
}

/// Every `<!ENTITY name "&#N;" >`, as the name and the code point.
fn declarations(text: &str, file: &str) -> Vec<(String, u32)> {
    let mut out = Vec::new();
    let mut rest = text;
    while let Some(at) = rest.find("<!ENTITY") {
        let after = &rest[at + "<!ENTITY".len()..];
        let end = after
            .find('>')
            .unwrap_or_else(|| panic!("{file}: a declaration that never closes"));
        let body = after[..end].trim();
        rest = &after[end + 1..];

        let (name, value) = body
            .split_once(char::is_whitespace)
            .unwrap_or_else(|| panic!("{file}: `{body}` is not a name and a value"));
        assert!(
            !name.is_empty() && name.chars().all(|c| c.is_ascii_alphanumeric()),
            "{file}: `{name}` is not a general entity's name"
        );
        let value = value.trim();
        let literal = value
            .strip_prefix('"')
            .and_then(|v| v.strip_suffix('"'))
            .unwrap_or_else(|| panic!("{file}: &{name};'s value `{value}` is not one literal"));
        // `&#38;#60;` is the reference `&#60;` with its ampersand escaped.
        let digits = literal
            .strip_prefix("&#38;#")
            .or_else(|| literal.strip_prefix("&#"))
            .and_then(|r| r.strip_suffix(';'))
            .filter(|d| !d.is_empty() && d.bytes().all(|b| b.is_ascii_digit()))
            .unwrap_or_else(|| {
                panic!("{file}: &{name}; is `{literal}`, not one decimal character reference")
            });
        let scalar: u32 = digits
            .parse()
            .unwrap_or_else(|_| panic!("{file}: &{name}; names no number"));
        out.push((name.to_string(), scalar));
    }
    out
}

/// XML 1.0 §2.2, the `Char` production — `text::is_xml_char`, restated
/// because a build script cannot reach the crate it builds.
const fn is_xml_char(c: char) -> bool {
    matches!(c,
        '\u{9}' | '\u{A}' | '\u{D}'
        | '\u{20}'..='\u{D7FF}'
        | '\u{E000}'..='\u{FFFD}'
        | '\u{10000}'..='\u{10FFFF}')
}
