//! The predefined CMaps of 9.7.5.2, read back out of the build-time tables.
//!
//! `build.rs` compiles Adobe's vendored `cmap-resources` into two blobs and
//! this reads them. The split is the `cmap-predefined` feature:
//!
//! - **names** — every registry CMap's name, writing mode, `usecmap` parent
//!   and codespace ranges. About ten kilobytes, always compiled in, because
//!   the codespaces are what decide where one code ends and the next begins
//!   and a build that gets that wrong mis-splits every Shift-JIS string
//!   before any mapping happens.
//! - **CIDs** — the code-to-CID ranges themselves, one deflate stream per
//!   CMap, about a megabyte. Present only with `cmap-predefined`, which is on
//!   by default. Without it the codespaces still answer, the CIDs do not, and
//!   [`super::CMap::is_approximate`] is true so a caller can say which CMap
//!   this build could not resolve rather than guessing one.
//!
//! Nothing here trusts the blob. It is generated by this repository's own
//! build script from data `cargo xtask vendor` checks, so a malformed one is
//! a broken build rather than a hostile document — but a decoder that indexes
//! blindly is a decoder that panics when someone reaches for `include_bytes!`
//! with a stale `OUT_DIR`, and ruling 1 is cheaper to keep than to restore.

/// Names, writing modes, parents and codespaces. Always present.
static NAMES: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/cmap_names.bin"));

/// Deflated code-to-CID tables. `build.rs` writes this empty when
/// `cmap-predefined` is off, and the reader is compiled out with it, so the
/// megabyte and the `tinker-pdf-filters` edge both disappear together.
#[cfg(feature = "cmap-predefined")]
static CIDS: &[u8] = include_bytes!(concat!(env!("OUT_DIR"), "/cmap_cids.bin"));

/// A CMap that has no parent, in the encoded form.
const NO_PARENT: u16 = u16::MAX;

/// One registry CMap's header: everything but its CID ranges.
pub(crate) struct Entry {
    /// Position in the table, which is also the index into the CID blob.
    pub index: u16,
    /// The `usecmap` parent's index, if it has one (9.7.5.3).
    pub parent: Option<u16>,
    /// `/WMode 1`.
    pub vertical: bool,
    /// Whether the source wrote `/WMode` at all. Every vendored CMap does;
    /// the flag is carried because 9.7.5.3 makes a child's declaration beat
    /// an inherited one, and "declared horizontal" is not "said nothing".
    pub wmode_declared: bool,
    /// `(byte length, low, high)`, in the registry's declaration order.
    pub codespaces: Vec<(u8, u32, u32)>,
}

/// The registry CMap of this name, if the registry has one.
pub(crate) fn entry(name: &[u8]) -> Option<Entry> {
    at(|found, _| found == name)
}

/// The registry CMap at this index.
pub(crate) fn entry_at(index: u16) -> Option<Entry> {
    at(|_, i| i == index)
}

/// Scans the name table for the first entry `want` accepts.
///
/// A scan rather than a binary search: the records are variable length, the
/// table is two hundred entries of a dozen bytes each, and this runs once per
/// font rather than once per glyph. A jump table would cost more bytes in the
/// blob than the scan costs in time.
fn at(want: impl Fn(&[u8], u16) -> bool) -> Option<Entry> {
    let mut r = Reader::new(NAMES);
    let count = r.u32()?;
    for index in 0..count {
        let name = r.bytes()?;
        let flags = r.u8()?;
        let parent = r.u16()?;
        let codespaces = r.codespaces()?;
        let index = u16::try_from(index).ok()?;
        if want(name, index) {
            return Some(Entry {
                index,
                parent: (parent != NO_PARENT).then_some(parent),
                vertical: flags & 1 != 0,
                wmode_declared: flags & 2 != 0,
                codespaces,
            });
        }
    }
    None
}

/// The code-to-CID ranges of the CMap at `index`, sorted by low code and
/// guaranteed disjoint — `build.rs` asserts both, which is what lets the
/// lookup binary-search.
///
/// `None` means this build has no CID data: either `cmap-predefined` is off,
/// or the blob is not the one this code was compiled against. Both are the
/// same thing to a caller — the mapping is not known — and neither is a
/// reason to invent one.
#[cfg(feature = "cmap-predefined")]
pub(crate) fn ranges(index: u16) -> Option<Vec<(u32, u32, u32)>> {
    let mut header = Reader::new(CIDS);
    let count = header.u32()?;
    if u32::from(index) >= count {
        return None;
    }
    // Fixed-width header: a count, then two words per CMap.
    let at = 4 + usize::from(index) * 8;
    let mut slot = Reader::new(CIDS.get(at..)?);
    let offset = slot.u32()? as usize;
    let length = slot.u32()? as usize;
    let payload = 4 + count as usize * 8;
    let packed = CIDS.get(payload + offset..payload + offset + length)?;

    // The tables are ours and their sizes are known, so the ceiling is a
    // guard against a corrupt blob rather than against a document.
    let limits = tinker_pdf_filters::Limits::new(8 << 20);
    let decoded = tinker_pdf_filters::flate_decode(packed, &limits, None).ok()?;
    if !decoded.complete {
        return None;
    }

    let mut r = Reader::new(&decoded.data);
    let n = r.varint()?;
    let mut out = Vec::with_capacity(usize::try_from(n).ok()?.min(1 << 16));
    let (mut low, mut cid) = (0u32, 0u32);
    for _ in 0..n {
        low = low.checked_add(u32::try_from(r.varint()?).ok()?)?;
        let span = u32::try_from(r.varint()?).ok()?;
        let high = low.checked_add(span)?;
        cid = cid.checked_add_signed(i32::try_from(unzigzag(r.varint()?)).ok()?)?;
        out.push((low, high, cid));
    }
    Some(out)
}

/// Without the tables there is nothing to read and nothing to guess.
#[cfg(not(feature = "cmap-predefined"))]
pub(crate) fn ranges(_index: u16) -> Option<Vec<(u32, u32, u32)>> {
    None
}

#[cfg(feature = "cmap-predefined")]
fn unzigzag(v: u64) -> i64 {
    ((v >> 1) as i64) ^ -((v & 1) as i64)
}

/// A bounds-checked cursor over a generated blob.
struct Reader<'a> {
    bytes: &'a [u8],
    pos: usize,
}

impl<'a> Reader<'a> {
    fn new(bytes: &'a [u8]) -> Reader<'a> {
        Reader { bytes, pos: 0 }
    }

    fn u8(&mut self) -> Option<u8> {
        let b = *self.bytes.get(self.pos)?;
        self.pos += 1;
        Some(b)
    }

    fn u16(&mut self) -> Option<u16> {
        let pair = self.bytes.get(self.pos..self.pos + 2)?;
        self.pos += 2;
        Some(u16::from_le_bytes([pair[0], pair[1]]))
    }

    fn u32(&mut self) -> Option<u32> {
        let quad = self.bytes.get(self.pos..self.pos + 4)?;
        self.pos += 4;
        Some(u32::from_le_bytes([quad[0], quad[1], quad[2], quad[3]]))
    }

    /// A length-prefixed byte string.
    fn bytes(&mut self) -> Option<&'a [u8]> {
        let len = usize::from(self.u8()?);
        let out = self.bytes.get(self.pos..self.pos + len)?;
        self.pos += len;
        Some(out)
    }

    fn varint(&mut self) -> Option<u64> {
        let mut value = 0u64;
        for shift in (0..64).step_by(7) {
            let byte = self.u8()?;
            value |= u64::from(byte & 0x7F).checked_shl(shift)?;
            if byte & 0x80 == 0 {
                return Some(value);
            }
        }
        None
    }

    fn codespaces(&mut self) -> Option<Vec<(u8, u32, u32)>> {
        let count = usize::from(self.u8()?);
        let mut out = Vec::with_capacity(count);
        for _ in 0..count {
            let bytes = self.u8()?;
            let low = u32::try_from(self.varint()?).ok()?;
            let high = low.checked_add(u32::try_from(self.varint()?).ok()?)?;
            out.push((bytes, low, high));
        }
        Some(out)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The vendored registry, as a count. If a re-vendoring changes it, that
    /// is a fact worth having stated somewhere rather than discovered.
    #[test]
    fn the_whole_registry_is_compiled_in() {
        let count = Reader::new(NAMES).u32().expect("the blob has a header");
        assert_eq!(count, 202, "202 CMaps were vendored");
        assert!(entry(b"90ms-RKSJ-H").is_some());
        assert!(entry(b"UniJIS-UCS2-H").is_some());
        assert!(
            entry(b"Identity-H").is_some(),
            "the registry defines it too"
        );
        assert!(entry(b"90ms-RKSJ-Q").is_none(), "and nothing else");
    }

    /// Every parent index resolves, and every CMap is reachable by its own
    /// index — the two directions the table is walked in.
    #[test]
    fn every_entry_round_trips_through_its_index() {
        let count = Reader::new(NAMES).u32().expect("the blob has a header");
        for index in 0..u16::try_from(count).expect("202 fits") {
            let entry = entry_at(index).expect("every index is an entry");
            assert_eq!(entry.index, index);
            if let Some(parent) = entry.parent {
                assert!(entry_at(parent).is_some(), "{index} names a lost parent");
            }
        }
    }

    /// A short, truncated or absent blob must answer `None`, not panic. This
    /// is the shape a stale `OUT_DIR` takes.
    #[test]
    fn a_truncated_blob_answers_nothing() {
        for len in 0..NAMES.len().min(64) {
            let mut r = Reader::new(&NAMES[..len]);
            let _ = r.u32();
            let _ = r.bytes();
            let _ = r.codespaces();
        }
        assert!(ranges(u16::MAX).is_none(), "past the end of the table");
    }
}
