//! Compiles the vendored UCD into static range tables.
//!
//! THIRDPARTY.md's promise about vendored data is that *"the raw files never
//! reach a released binary"*, and this is the half of it that keeps the
//! promise: five text files in, one `.rs` out, and nothing under `data/` is
//! opened at run time. `tinker-pdf-font/build.rs` does the same thing for
//! Adobe's CMap registry and this file is deliberately in its register.
//!
//! # The classes are emitted as enum variants, not as indices
//!
//! Every row of the generated table names `Class::AL` rather than the number
//! `2`. That costs a few bytes of generated source and buys the thing an index
//! cannot: **a Line_Break class this crate does not know about fails to
//! build.** Unicode 17.0 added `AP`, `AK`, `AS`, `VF` and `VI` after 15.0, and
//! a build that mapped an unknown name onto a default would have laid out
//! Brahmi-family scripts as though the additions had never happened — which is
//! the shape of failure this whole gap is organised around. Re-vendoring a
//! later UCD therefore breaks the build until somebody reads the new class,
//! which is the correct outcome.
//!
//! # What the four property files are each for
//!
//! - `LineBreak.txt` is the Line_Break property, which is the algorithm.
//! - `EastAsianWidth.txt` is needed by UAX #14 itself, not by measurement:
//!   LB30's parenthesis rules exclude East Asian Wide, Full-width and
//!   Half-width forms, so a build without it breaks `A(` and `A（` the same
//!   way and one of the two is wrong.
//! - `DerivedGeneralCategory.txt` supplies two facts. `SA` resolves to `CM`
//!   when the character is `Mn` or `Mc` and to `AL` otherwise (LB1), and
//!   LB30b's second clause is about **unassigned** pictographs, so `Cn` is
//!   needed to know which those are.
//! - `emoji-data.txt` is `Extended_Pictographic`, LB30b's other half.
//!
//! `LineBreakTest.txt` is not read here. It is the conformance oracle and it
//! is read by a test, because a table compiled from its own test data would
//! prove nothing.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let data = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("cargo sets this"))
        .join("data")
        .join("ucd");
    for file in [
        "LineBreak.txt",
        "EastAsianWidth.txt",
        "DerivedGeneralCategory.txt",
        "emoji-data.txt",
    ] {
        println!("cargo:rerun-if-changed=data/ucd/{file}");
    }
    println!("cargo:rerun-if-changed=build.rs");

    let mut out = String::new();
    out.push_str("// Generated by build.rs from the vendored UCD. Do not edit.\n");

    line_break(&data, &mut out);
    east_asian_width(&data, &mut out);
    binary_property(
        &data.join("emoji-data.txt"),
        Some("Extended_Pictographic"),
        "EXTENDED_PICTOGRAPHIC",
        &mut out,
    );
    binary_property(
        &data.join("DerivedGeneralCategory.txt"),
        Some("Cn"),
        "UNASSIGNED",
        &mut out,
    );
    // LB15a and LB15b are about the *quotation* classes split by general
    // category — `QU ∩ Pi` opens a quotation and `QU ∩ Pf` closes one — so the
    // two categories are needed as sets of their own. Without them a build
    // treats “ and ” alike and breaks after an opening quote.
    binary_property(
        &data.join("DerivedGeneralCategory.txt"),
        Some("Pi"),
        "INITIAL_PUNCTUATION",
        &mut out,
    );
    binary_property(
        &data.join("DerivedGeneralCategory.txt"),
        Some("Pf"),
        "FINAL_PUNCTUATION",
        &mut out,
    );
    combining(&data, &mut out);

    let target = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets this")).join("ucd.rs");
    std::fs::write(&target, out).expect("the generated table could not be written");
}

/// One `code..code ; value # comment` file, as `(first, last, value)`.
///
/// The UCD's own format, and the two things worth being careful about are both
/// in `LineBreakTest.txt`'s neighbours: the published files are CRLF and the
/// value field may be followed by a `#` comment with no space in front of it —
/// `emoji-data.txt` writes `; Extended_Pictographic# E0.6`.
fn rows(path: &Path) -> Vec<(u32, u32, String)> {
    let text = std::fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("the vendored UCD is missing: {} ({e})", path.display()));
    let mut out = Vec::new();
    for line in text.lines() {
        let line = line.trim_end_matches('\r');
        let body = match line.find('#') {
            // A `#` that starts the line is a comment; one after a value ends
            // the value. `emoji-data.txt` writes both shapes.
            Some(0) => continue,
            Some(at) => &line[..at],
            None => line,
        };
        let mut fields = body.split(';');
        let (Some(codes), Some(value)) = (fields.next(), fields.next()) else {
            continue;
        };
        let value = value.trim();
        if value.is_empty() {
            continue;
        }
        let codes = codes.trim();
        let (first, last) = match codes.split_once("..") {
            Some((a, b)) => (hex(a), hex(b)),
            None => (hex(codes), hex(codes)),
        };
        out.push((first, last, value.to_string()));
    }
    assert!(!out.is_empty(), "no rows in {}", path.display());
    out
}

fn hex(text: &str) -> u32 {
    u32::from_str_radix(text.trim(), 16)
        .unwrap_or_else(|e| panic!("{text:?} is not a code point ({e})"))
}

/// Merges a code-point map into the fewest sorted ranges that describe it.
fn ranges(map: &BTreeMap<u32, String>) -> Vec<(u32, u32, String)> {
    let mut out: Vec<(u32, u32, String)> = Vec::new();
    for (code, value) in map {
        match out.last_mut() {
            Some((_, last, previous)) if *last + 1 == *code && previous == value => *last = *code,
            _ => out.push((*code, *code, value.clone())),
        }
    }
    out
}

/// The Line_Break property, exactly as the file states it and **not** with the
/// block defaults its own header describes.
///
/// The header lists four ranges whose *unassigned* code points default to `ID`
/// or `PR`, and applying them looks like the careful thing to do. It is wrong,
/// and Unicode's own conformance file is what says so: the file already carries
/// those defaults as explicit rows — `1F02C..1F02F ; ID # Cn` is a reserved
/// range written out — so the header describes what the file *has done*, not
/// what a reader must do. Filling them in a second time gives U+1F8FF, which
/// is unassigned and inside the header's `1F000..1FAFF`, the class `ID` where
/// `LineBreakTest.txt` says `XX`; ten conformance cases fail on exactly that
/// and nothing else in this repository would ever have noticed.
fn line_break(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(&data.join("LineBreak.txt")) {
        for code in first..=last {
            map.insert(code, value.clone());
        }
    }
    emit(out, "LINE_BREAK", "Class", &ranges(&map));
}

fn east_asian_width(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(&data.join("EastAsianWidth.txt")) {
        for code in first..=last {
            map.insert(code, value.clone());
        }
    }
    // No block defaults here either, for the reason above: the file writes its
    // own out, and a second pass over them disagrees with the conformance data.
    emit(out, "EAST_ASIAN", "Eaw", &ranges(&map));
}

/// A file's rows whose value is one particular name, as bare ranges.
fn binary_property(path: &Path, wanted: Option<&str>, name: &str, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(path) {
        if wanted.is_some_and(|w| w != value) {
            continue;
        }
        for code in first..=last {
            map.insert(code, String::new());
        }
    }
    let merged = ranges(&map);
    let mut body = String::new();
    for (first, last, _) in &merged {
        let _ = writeln!(body, "    ({first:#x}, {last:#x}),");
    }
    let _ = writeln!(
        out,
        "/// {} ranges, from the vendored UCD.\npub static {name}: &[(u32, u32)] = &[\n{body}];",
        merged.len()
    );
}

/// `Mn` and `Mc` together, which is LB1's test for whether an `SA` character
/// resolves to `CM` rather than to `AL`.
fn combining(data: &Path, out: &mut String) {
    let mut map: BTreeMap<u32, String> = BTreeMap::new();
    for (first, last, value) in rows(&data.join("DerivedGeneralCategory.txt")) {
        if value != "Mn" && value != "Mc" {
            continue;
        }
        for code in first..=last {
            map.insert(code, String::new());
        }
    }
    let merged = ranges(&map);
    let mut body = String::new();
    for (first, last, _) in &merged {
        let _ = writeln!(body, "    ({first:#x}, {last:#x}),");
    }
    let _ = writeln!(
        out,
        "/// General_Category Mn or Mc, for LB1's SA resolution.\n\
         pub static COMBINING: &[(u32, u32)] = &[\n{body}];",
    );
}

fn emit(out: &mut String, name: &str, kind: &str, merged: &[(u32, u32, String)]) {
    let mut body = String::new();
    for (first, last, value) in merged {
        let _ = writeln!(body, "    ({first:#x}, {last:#x}, {kind}::{value}),");
    }
    let _ = writeln!(
        out,
        "/// {} ranges, from the vendored UCD. The value is an enum variant \
         rather than an index, so a class this crate does not know **does not \
         build**.\npub static {name}: &[(u32, u32, {kind})] = &[\n{body}];",
        merged.len()
    );
}
