//! CSS 2.2 §9.5: where a float goes, and the band it leaves beside it.
//!
//! # The nine constraints are a set
//!
//! §9.5.1 is not a procedure. It is nine numbered constraints on the *result*,
//! and an implementation is free to reach that result however it likes so long
//! as all nine hold at once. That is exactly what makes them dangerous to
//! implement: **eight of them produce a page that looks right**, because the
//! ninth binds only on the arrangement that needed it, and the arrangement that
//! needed it is one figure in one chapter of one book.
//!
//! So each of the nine is written below as its own named step, each one is the
//! only place its rule is decided, and each has a fixture in
//! [`crate::tests`] that fails when that step alone is broken. The numbering
//! here is §9.5.1's own:
//!
//! 1. a left float's left outer edge is not left of its containing block's
//!    left edge, and mirrored for a right float — [`Fit::lower`]/[`Fit::upper`];
//! 2. a left float does not overlap an **earlier left** float: it is either
//!    clear to its right or below it — [`FloatContext::edge`], same side;
//! 3. a left float's right outer edge is not right of an **earlier right**
//!    float's left outer edge — [`FloatContext::edge`], the other side;
//! 4. a float's outer top is not above the top of its containing block —
//!    [`Ceilings::containing_top`];
//! 5. nor above the top of any **box** generated by an earlier element —
//!    [`Ceilings::earlier_box_top`];
//! 6. nor above the top of any **line box** holding an earlier box —
//!    [`Ceilings::earlier_line_top`];
//! 7. a left float that has another left float to its left does not have its
//!    right outer edge right of the containing block's right edge — which is
//!    **not** rule 1 and **not** rule 3: it is the rule that sends the second
//!    of two floats down a line, and the rule whose over-application sends a
//!    *single* float wider than its container down a line it should not go
//!    down — [`Fit::stacked`];
//! 8. a float is placed as high as possible — [`FloatContext::place`]'s
//!    candidate scan, lowest first;
//! 9. and then as far to the left (or right) as possible — [`Fit::extreme`].
//!
//! # What 4, 5 and 6 measure, and why it is the border edge
//!
//! Rules 4 to 6 are worded *"the outer top"*, which is the margin edge. This
//! build clamps against the **border** edge of the earlier boxes in rules 5 and
//! 6 and against the containing block's **content** edge in rule 4, and the two
//! choices differ only where a margin is negative — a margin edge that a
//! negative margin has pulled above its own border box is not a position any
//! content occupies, and clamping a float to it would put the float above the
//! text it is meant to sit beside. Every fixture for these three rules is built
//! out of negative margins for that reason: with positive margins alone the
//! three are indistinguishable from each other and from doing nothing at all,
//! and a fixture that cannot tell them apart is the thing this milestone is
//! organised against.

use tinker_pdf_css::property::{Clear, Float};

use crate::{Budget, Refusal};

/// Slack for the geometric comparisons, in points.
///
/// The same figure and the same argument as [`crate::fragment`]'s: a float
/// whose right edge lands on the containing block's to within a thousandth of a
/// point fits, and the alternative is an accumulated rounding error sending a
/// figure down a line for no reason a reader could see.
const EPSILON: f64 = 1e-6;

/// A float's **margin** box, once placed, in flow coordinates.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct Placed {
    /// `left` or `right`. Never [`Float::None`] — a thing that is not floated
    /// is not in here.
    pub side: Float,
    /// Margin-box left edge.
    pub left: f64,
    /// Margin-box right edge.
    pub right: f64,
    /// Margin-box top edge.
    pub top: f64,
    /// Margin-box bottom edge.
    pub bottom: f64,
}

/// Rules 4, 5 and 6: the three separate reasons a float may not rise.
///
/// One struct with three named fields rather than one `f64`, because they are
/// three rules with three fixtures and a single pre-maxed number would let any
/// two of them be deleted with the third covering for them.
#[derive(Clone, Copy, Debug, PartialEq)]
pub(crate) struct Ceilings {
    /// Rule 4: the content top of the float's containing block.
    pub containing_top: f64,
    /// Rule 5: the lowest border-box top of any box an earlier element
    /// generated, floated or not.
    pub earlier_box_top: f64,
    /// Rule 6: the lowest top of any line box holding earlier content.
    pub earlier_line_top: f64,
}

/// The half-open range of left edges rules 1, 2, 3 and 7 leave at one
/// candidate `y`.
///
/// Named fields rather than a tuple so that rule 9 — *which end of the range
/// the float takes* — is a decision of its own and not a term of somebody
/// else's expression.
#[derive(Clone, Copy, Debug)]
struct Fit {
    /// The leftmost the margin box may start: rules 1 and 2 for a left float,
    /// rules 3 and 7 for a right one.
    lower: f64,
    /// The rightmost it may start: rules 3 and 7 for a left float, rules 1 and
    /// 2 for a right one.
    upper: f64,
}

impl Fit {
    /// Rule 9: as far to the left as possible for a left float, as far to the
    /// right as possible for a right float.
    ///
    /// The whole of rule 9, in one place, so that a build that put floats at
    /// the wrong end of the range fails one fixture and not nine.
    fn extreme(&self, side: Float) -> f64 {
        match side {
            Float::Right => self.upper,
            _ => self.lower,
        }
    }
}

/// The floats of one block formatting context, in the order they were placed.
///
/// A float establishes a new BFC for its own contents, so a float inside a
/// float is placed against a **fresh** context — which is why this is a value
/// the builder swaps rather than one it appends to for ever.
#[derive(Clone, Debug, Default)]
pub(crate) struct FloatContext {
    placed: Vec<Placed>,
}

impl FloatContext {
    /// Whether anything is floated here at all.
    pub fn is_empty(&self) -> bool {
        self.placed.is_empty()
    }

    /// How many floats one scan of this context examines.
    ///
    /// The unit [`crate::limits::MAX_LAYOUT_WORK`] is counted in, and public
    /// so that the caller can charge for a scan **before** starting it.
    pub fn len(&self) -> usize {
        self.placed.len()
    }

    /// Records a placed float. Only [`FloatContext::place`]'s answers belong
    /// in here.
    pub fn push(&mut self, float: Placed) {
        self.placed.push(float);
    }

    /// The inner edge of the floats of one side that cross a vertical range,
    /// or `None` where none does.
    ///
    /// This is rule 2 when it is asked about the float's own side and rule 3
    /// when it is asked about the other one, and it is one function because the
    /// geometry is one question: *how far in do the floats on that side reach,
    /// between these two heights?*
    fn edge(&self, side: Float, top: f64, bottom: f64) -> Option<f64> {
        let mut found: Option<f64> = None;
        for float in &self.placed {
            if float.side != side {
                continue;
            }
            // A float that ends exactly where the range begins is not beside
            // it. The strict comparison is what lets a line sit immediately
            // under a float rather than one line lower.
            if float.bottom <= top + EPSILON || float.top >= bottom - EPSILON {
                continue;
            }
            let inner = match side {
                Float::Right => float.left,
                _ => float.right,
            };
            found = Some(match (found, side) {
                (None, _) => inner,
                (Some(previous), Float::Right) => previous.min(inner),
                (Some(previous), _) => previous.max(inner),
            });
        }
        found
    }

    /// The measure left for a line box between `top` and `bottom`, given the
    /// containing block's own content edges.
    ///
    /// Both edges, because a line between a left and a right float is narrowed
    /// from both sides and a build that returned one number would put the text
    /// under the wrong one.
    pub fn band(&self, top: f64, bottom: f64, cb_left: f64, cb_right: f64) -> (f64, f64) {
        let left = self
            .edge(Float::Left, top, bottom)
            .map_or(cb_left, |edge| edge.max(cb_left));
        let right = self
            .edge(Float::Right, top, bottom)
            .map_or(cb_right, |edge| edge.min(cb_right));
        (left, right.max(left))
    }

    /// The next float bottom below `y`, which is where a line box that does
    /// not fit beside the floats here has to go looking next.
    ///
    /// The bottoms of the floats and not `y` plus a line: §9.5's *"shifted
    /// downward until either it fits or there are no more floats"* is a walk
    /// over the floats, and stepping down a line at a time would put the line
    /// wherever the arithmetic landed rather than under the thing that
    /// displaced it.
    pub fn next_bottom(&self, y: f64) -> Option<f64> {
        self.placed
            .iter()
            .map(|float| float.bottom)
            .filter(|bottom| *bottom > y + EPSILON)
            .fold(None, |seen: Option<f64>, bottom| {
                Some(seen.map_or(bottom, |best| best.min(bottom)))
            })
    }

    /// §9.5.2: the bottom edge a box with this `clear` value must be pushed
    /// below, or `None` when nothing on those sides is floated.
    ///
    /// `None` and `Some(a bottom above the box)` are different answers to
    /// different questions — the first is *there was nothing to clear*, which
    /// is not a fault, and the second is *there was, and it is already
    /// cleared*, which is where clearance is zero and margins still do not
    /// collapse through.
    pub fn clearance_bottom(&self, clear: Clear) -> Option<f64> {
        let wanted = |side: Float| {
            matches!(
                (clear, side),
                (Clear::Both, _) | (Clear::Left, Float::Left) | (Clear::Right, Float::Right)
            )
        };
        let mut bottom: Option<f64> = None;
        for float in &self.placed {
            if !wanted(float.side) {
                continue;
            }
            bottom = Some(bottom.map_or(float.bottom, |seen: f64| seen.max(float.bottom)));
        }
        bottom
    }

    /// Places one float's margin box: §9.5.1, all nine.
    ///
    /// `hint` is the float's **static position** — the top of the margin box it
    /// would have had in flow, which is where §9.5.1's note about a float
    /// between two collapsing margins puts it. `width` and `height` are the
    /// margin box's. The answer is the margin box's top-left corner.
    ///
    /// # Errors
    /// [`Refusal::TooMuchLayoutWork`] where the book's float total is spent.
    /// The charge is one unit per float this call will examine, taken before
    /// each scan: §9.5.1's rules 2, 3 and 7 look at every float already placed
    /// and rule 8 may do it once per candidate height, so the cost of placing
    /// the last float of a book is the number of floats before it and the cost
    /// of a book is the square of them.
    #[allow(clippy::too_many_arguments)]
    pub fn place(
        &self,
        side: Float,
        width: f64,
        height: f64,
        hint: f64,
        ceilings: &Ceilings,
        cb_left: f64,
        cb_right: f64,
        budget: &mut Budget,
    ) -> Result<(f64, f64), Refusal> {
        // Rules 4, 5 and 6, each on its own line, each the only place it is
        // applied.
        let mut top = hint;
        top = top.max(ceilings.containing_top);
        top = top.max(ceilings.earlier_box_top);
        top = top.max(ceilings.earlier_line_top);

        // Rule 8, *"a floating box must be placed as high as possible"*: the
        // candidates are the ceiling and the bottom of every float that is
        // below it, tried in that order. A build that scanned them in any other
        // order satisfies every other rule and puts a narrow figure below a
        // wide one it would have fitted beside.
        let mut candidates: Vec<f64> = vec![top];
        budget.spend_layout(self.placed.len())?;
        for float in &self.placed {
            if float.bottom > top + EPSILON {
                candidates.push(float.bottom);
            }
        }
        candidates.sort_by(|a, b| a.partial_cmp(b).unwrap_or(std::cmp::Ordering::Equal));
        // The last candidate is below every float here, so rules 2, 3 and 7
        // are vacuous there and the scan always terminates with an answer.
        // `unwrap_or` below is therefore unreachable and is a default rather
        // than a fallback.
        for y in candidates {
            // Two scans of the placed floats: this float's own side and the
            // other one.
            budget.spend_layout(2 * self.placed.len())?;
            if let Some(fit) = self.fit(side, width, height, y, cb_left, cb_right) {
                return Ok((fit.extreme(side), y));
            }
        }
        // Unreachable under the rules as written — the last candidate is below
        // every float here, so rules 2, 3 and 7 are vacuous there and rule 1
        // alone cannot reject a position. It is the **static** position rather
        // than the bottom one because that is what a box does when its
        // constraints cannot be met: it stays where it was written and
        // overflows.
        Ok((
            match side {
                Float::Right => cb_right - width,
                _ => cb_left,
            },
            top,
        ))
    }

    /// Rules 1, 2, 3 and 7 at one candidate height, or `None` where they
    /// cannot all hold at once.
    ///
    /// **Rule 1 constrains one edge and not two.** For a left float it is the
    /// *left* outer edge that may not leave the containing block; nothing in
    /// §9.5.1 stops a lone left float's right edge overflowing, and rule 7 is
    /// the one that stops it — but only once there is another left float
    /// beside it. A build that clamped both edges here would pass every
    /// two-float fixture and send a single wide figure down a line for no
    /// reason.
    fn fit(
        &self,
        side: Float,
        width: f64,
        height: f64,
        y: f64,
        cb_left: f64,
        cb_right: f64,
    ) -> Option<Fit> {
        let bottom = y + height;
        // Rule 2 asks about this float's own side and rule 3 about the other,
        // and it is one function because the geometry is one question asked
        // twice.
        let same = self.edge(side, y, bottom);
        let other = self.edge(opposite(side), y, bottom);
        let mut lower = f64::NEG_INFINITY;
        let mut upper = f64::INFINITY;
        match side {
            Float::Right => {
                upper = cb_right - width; // rule 1, mirrored
                if let Some(edge) = same {
                    upper = upper.min(edge - width); // rule 2
                }
                if let Some(edge) = other {
                    lower = lower.max(edge); // rule 3
                }
                if same.is_some_and(|edge| edge < cb_right - EPSILON) {
                    lower = lower.max(cb_left); // rule 7
                }
            }
            _ => {
                lower = cb_left; // rule 1
                if let Some(edge) = same {
                    lower = lower.max(edge); // rule 2
                }
                if let Some(edge) = other {
                    upper = upper.min(edge - width); // rule 3
                }
                if same.is_some_and(|edge| edge > cb_left + EPSILON) {
                    upper = upper.min(cb_right - width); // rule 7
                }
            }
        }
        if lower > upper + EPSILON {
            return None;
        }
        Some(Fit { lower, upper })
    }
}

/// The other side.
fn opposite(side: Float) -> Float {
    match side {
        Float::Right => Float::Left,
        _ => Float::Right,
    }
}
